# Generated by Django 3.1.7 on 2021-09-18 22:05

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Xiaomi', 'Xiaomi'), ('Otro', 'Otro')], default='Apple', max_length=15)),
                ('tipo', models.CharField(choices=[('Cargador', 'Cargador'), ('Cable', 'Cable'), ('Adaptador', 'Adaptador'), ('Audífonos', 'Audífonos'), ('Protector', 'Protector'), ('Mica', 'Mica'), ('Otro', 'Otro')], default='Cargador', max_length=15)),
                ('conexion', models.CharField(blank=True, choices=[('Lightning', 'Lightning'), ('Tipo C', 'Tipo C'), ('Micro USB', 'Micro USB'), ('Inalámbrica', 'Inalámbrica'), ('Normal', 'Normal'), ('Otra', 'Otra')], default='Lightning', max_length=15, null=True)),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_venta', models.DateField(default=datetime.date(2021, 9, 18))),
                ('proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_compra', models.FloatField(blank=True, null=True)),
                ('monto_venta', models.FloatField()),
                ('entrega', models.CharField(blank=True, choices=[('Entregado', 'Entregado'), ('Envio servientrega', 'Envio servientrega'), ('Envio cooperativa', 'Envio cooperativa')], default='Entregado', max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Accesorios',
                'ordering': ['marca', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('Open box', 'Open box'), ('Sellado', 'Sellado')], default='Open box', max_length=10)),
                ('capacidad', models.CharField(choices=[('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB'), ('2TB', '2TB')], max_length=5)),
                ('tamanio', models.FloatField(default=11)),
                ('imei', models.IntegerField(blank=True, null=True)),
                ('serial', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_compra', models.DateField(default=datetime.date(2021, 9, 18))),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_compra', models.FloatField(null=True)),
                ('monto_venta', models.FloatField(blank=True, null=True)),
                ('vendido', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=20)),
                ('entrega', models.CharField(blank=True, choices=[('Entregado', 'Entregado'), ('Envio servientrega', 'Envio servientrega'), ('Envio cooperativa', 'Envio cooperativa')], default='Entregado', max_length=20, null=True)),
                ('llego_cargador', models.BooleanField(default=False)),
                ('llego_audifonos', models.BooleanField(default=False)),
                ('sefue_cargador', models.BooleanField(default=False)),
                ('sefue_audifonos', models.BooleanField(default=False)),
                ('precio_cargador', models.DecimalField(blank=True, decimal_places=2, default=5.5, max_digits=5, null=True)),
                ('precio_audifonos', models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='ModeloDispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Otra', 'Otra')], default='Apple', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Modelos de dispositivos',
                'ordering': ['marca', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple')], default='Apple', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Modelos de teléfono',
                'ordering': ['marca', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Monedero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Monederos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('Open box', 'Open box'), ('Sellado', 'Sellado')], default='Open box', max_length=10)),
                ('capacidad', models.CharField(choices=[('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB')], max_length=5)),
                ('imei', models.BigIntegerField()),
                ('imei2', models.BigIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('bateria', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('fecha_compra', models.DateField(default=datetime.date(2021, 9, 18))),
                ('proveedor', models.CharField(max_length=50)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('nro_cliente', models.CharField(blank=True, max_length=15, null=True)),
                ('monto_compra', models.FloatField(blank=True, null=True)),
                ('monto_venta', models.FloatField(blank=True, null=True)),
                ('vendido', models.BooleanField(default=False)),
                ('entrega', models.CharField(blank=True, choices=[('Entregado', 'Entregado'), ('Envio servientrega', 'Envio servientrega'), ('Envio cooperativa', 'Envio cooperativa')], default='Entregado', max_length=20, null=True)),
                ('llego_cargador', models.BooleanField(default=False)),
                ('llego_cargador_rapido', models.BooleanField(default=False)),
                ('llego_audifonos', models.BooleanField(default=False)),
                ('sefue_cargador', models.BooleanField(default=False)),
                ('sefue_cargador_rapido', models.BooleanField(default=False)),
                ('sefue_audifonos', models.BooleanField(default=False)),
                ('precio_cargador', models.DecimalField(blank=True, decimal_places=2, default=5.5, max_digits=5, null=True)),
                ('precio_cargador_rapido', models.DecimalField(blank=True, decimal_places=2, default=13, max_digits=5, null=True)),
                ('precio_audifonos', models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=5, null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='principal.modelotelefono')),
            ],
            options={
                'verbose_name_plural': 'Teléfonos',
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date(2021, 9, 18))),
                ('hora', models.TimeField(default=datetime.time(17, 5, 34, 326424))),
                ('tipo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia banco', 'Transferencia banco'), ('Tarjeta de crédito', 'Tarjeta de crédito')], default='Efectivo', max_length=20)),
                ('motivo', models.CharField(blank=True, default='Ninguno', max_length=100, null=True)),
                ('dinero', models.FloatField(default=0)),
                ('accesorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='principal.accesorio')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='principal.dispositivo')),
                ('monedero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='principal.monedero')),
                ('telefono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='principal.telefono')),
            ],
            options={
                'verbose_name_plural': 'Transacciones',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='telefono',
            name='monederos',
            field=models.ManyToManyField(through='principal.Transaccion', to='principal.Monedero'),
        ),
        migrations.AddField(
            model_name='monedero',
            name='accesorios',
            field=models.ManyToManyField(through='principal.Transaccion', to='principal.Accesorio'),
        ),
        migrations.AddField(
            model_name='monedero',
            name='dispositivos',
            field=models.ManyToManyField(through='principal.Transaccion', to='principal.Dispositivo'),
        ),
        migrations.AddField(
            model_name='monedero',
            name='telefonos',
            field=models.ManyToManyField(through='principal.Transaccion', to='principal.Telefono'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='principal.modelodispositivo'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='monederos',
            field=models.ManyToManyField(through='principal.Transaccion', to='principal.Monedero'),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='monederos',
            field=models.ManyToManyField(through='principal.Transaccion', to='principal.Monedero'),
        ),
    ]
